# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('datefrom', models.DateTimeField(max_length=20)),
                ('dateto', models.DateTimeField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='loginAndRegistration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripdestination', to='Trips.Destination')),
                ('trip_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripuser', to='loginAndRegistration.User')),
            ],
        ),
    ]
